name: "bribot"
author: "Mathilde Hermet"
license: "Apache-2.0"
short: "CTF bot for Discord server."
long: "A CLI tool to auto configure and send discord message with CTF url, timeline, team name, team password etc."

commands:
  - name: "reminder"
    short: "Remind CTF url, timelines adn credentials."
    long: "Enroll in a specific CTF challenge."
    flags:
      - name: "dry-run"
        shorthand: "d"
        usage: "Perform a dry run to visualize message without sending it."
        type: "bool"
      - name: "discord-webhook"
        shorthand: "w"
        usage: "Discord webhook URL to send message."
        type: "string"
      - name: "ctf-url"
        shorthand: "u"
        usage: "CTF URL to enroll."
        type: "string"
      - name: "team-name"
        shorthand: "n"
        usage: "Team name to enroll."
        type: "string"
      - name: "team-password"
        shorthand: "p"
        usage: "Team password to enroll."
        type: "string"
      - name: "start-time"
        shorthand: "s"
        usage: "CTF start time. Format should be 'YYYY-MM-DD HH:MM:SS TZ'."
        type: "string"
      - name: "end-time"
        shorthand: "e"
        usage: "CTF end time. Format should be 'YYYY-MM-DD HH:MM:SS TZ'."
        type: "string"
      

